# Generated by Django 5.2.17 on 2026-09-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=150)),
                ('salary_from', models.PositiveIntegerField()),
                ('is_remote', models.BooleanField(default=False)),
            ],
        ),
    ]
